#!/bin/bash
function print_help {
  echo 'Usage: ftwmcmd <command> <dimension> <direction>'
  echo
  echo '<command> ::= "increment" | "arrange"'
  echo '<dimension> ::= "width" | "height"'
  echo '<direction> ::= "-1" | "1"'
}
function call_method {
  dbus-send --dest=com.github.brainwave0.ftwm --type=method_call /com/github/brainwave0/ftwm/interface com.github.brainwave0.ftwm.interface.$@
}
if [[ $# == 3 && $1 == "increment" && ($2 == "width" || $2 == "height") && ($3 -eq -1 || $3 -eq 1) ]]; then
  call_method Increment string:$2 int16:$3
elif [[ $# == 1 && $1 == "arrange" ]]; then
  call_method Arrange
elif [[ $# == 1 && $1 == "kill" ]]; then
    call_method Kill
else
  print_help
fi
